#!/usr/bin/python
import getpass
import sys
import telnetlib

HOST = "localhost"
user = "root"
password = "dbps"

tn = telnetlib.Telnet("cdetts2",2004)

tn.write("\n");
if password:
    tn.read_until("[VxWorks Boot]:")
    tn.write("c\n")


tn.write("dc\n")
tn.write("0\n");
tn.write("sbs1\n");
tn.write("/site/coda/kern/5.5/vx2400_v2\n");
tn.write("129.57.37.59:fffffe00\n");
tn.write("\n");
tn.write("129.57.36.67\n");
tn.write("129.57.36.1\n");
tn.write("adaq\n");
tn.write("Gmp!2018\n");
tn.write("0x20\n");
tn.write("sbsvme15\n");
tn.write("/home/adaq/vxworks/sbsvme15_sbs2.boot\n");
tn.write("\n");
tn.write("p\n");
print tn.read_until("[VxWorks Boot]:");
tn.write("@\n");
print tn.read_until("Starting at 0x100000...")
print tn.read_until("executing startup script")

exit();
#exit()
