// This file is automatically generated.
import java.util.*;
public class EmuTerm__Build extends Hashtable {
  EmuTerm__Build() {
    put("dateString", "02/19/15 at 03:38:54PM EST");
    put("versionString", "2.0");
    put("version", new Integer(2));
    put("revision", new Integer(0));
    put("update", new Integer(0));
    put("build", new Integer(96));
  }
}
