// This file is automatically generated.
import java.util.*;
public class WebTerm__Build extends Hashtable {
  WebTerm__Build() {
    put("dateString", "02/13/15 at 03:25:16PM EST");
    put("versionString", "2.0");
    put("version", new Integer(2));
    put("revision", new Integer(0));
    put("update", new Integer(0));
    put("build", new Integer(29));
  }
}
