/********************************************************************
* SBSDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SBSDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSBSDict();
extern void G__cpp_setup_inheritanceSBSDict();
extern void G__cpp_setup_typetableSBSDict();
extern void G__cpp_setup_memvarSBSDict();
extern void G__cpp_setup_globalSBSDict();
extern void G__cpp_setup_memfuncSBSDict();
extern void G__cpp_setup_funcSBSDict();
extern void G__set_cpp_environmentSBSDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HcalDetector.h"
#include "HcalApparatus.h"
#include "FbusDetector.h"
#include "FbusApparatus.h"
#include "CdetDetector.h"
#include "CdetApparatus.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SBSDictLN_TClass;
extern G__linked_taginfo G__SBSDictLN_TBuffer;
extern G__linked_taginfo G__SBSDictLN_TMemberInspector;
extern G__linked_taginfo G__SBSDictLN_TObject;
extern G__linked_taginfo G__SBSDictLN_TNamed;
extern G__linked_taginfo G__SBSDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__SBSDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SBSDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SBSDictLN_TClonesArray;
extern G__linked_taginfo G__SBSDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SBSDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SBSDictLN_TDatime;
extern G__linked_taginfo G__SBSDictLN_THaEvData;
extern G__linked_taginfo G__SBSDictLN_THaAnalysisObject;
extern G__linked_taginfo G__SBSDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__SBSDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__SBSDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SBSDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SBSDictLN_maplEstringcOunsignedsPintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SBSDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SBSDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SBSDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SBSDictLN_THaDetectorBase;
extern G__linked_taginfo G__SBSDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SBSDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SBSDictLN_THaApparatus;
extern G__linked_taginfo G__SBSDictLN_THaDetector;
extern G__linked_taginfo G__SBSDictLN_THaSpectrometerDetector;
extern G__linked_taginfo G__SBSDictLN_THaNonTrackingDetector;
extern G__linked_taginfo G__SBSDictLN_HcalDetector;
extern G__linked_taginfo G__SBSDictLN_HcalApparatus;
extern G__linked_taginfo G__SBSDictLN_FbusDetector;
extern G__linked_taginfo G__SBSDictLN_FbusApparatus;
extern G__linked_taginfo G__SBSDictLN_CdetDetector;
extern G__linked_taginfo G__SBSDictLN_CdetDetectorcLcLDataDest;
extern G__linked_taginfo G__SBSDictLN_CdetApparatus;

/* STUB derived class for protected member access */
